[package]
name = "p2p-file-transfer"
version = "0.2.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "Peer-to-peer file transfer and conversion system using libp2p"
license = "MIT"

[dependencies]
# Core libp2p with all required features
libp2p = { version = "0.56", features = [
    "tcp", 
    "noise", 
    "yamux", 
    "swarm", 
    "identify", 
    "ping", 
    "request-response",
    "macros"
] }

# Async runtime and utilities
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
async-trait = "0.1"

# Serialization and data handling
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
uuid = { version = "1.0", features = ["v4", "serde"] }

# File conversion dependencies
genpdf = "0.2"
pdf-extract = "0.7"

# Error handling and logging
anyhow = "1.0"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# CLI and configuration
clap = { version = "4.5", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"

[dev-dependencies]
tempfile = "3.0"
tokio-test = "0.4"

[[bin]]
name = "p2p-file-node"
path = "bin/file_node.rs"

[[bin]]
name = "p2p-file-client"
path = "bin/file_client.rs"

[[example]]
name = "simple_transfer"
path = "examples/simple_transfer.rs"

[[example]]
name = "batch_conversion"
path = "examples/batch_conversion.rs"
