[package]
name = "p2p-file-converter-cli"
version = "1.0.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "Command-line interface for P2P file converter with validation"
license = "MIT"

[[bin]]
name = "p2p-converter"
path = "p2p_cli.rs"

[dependencies]
# CLI parsing with derive macros
clap = { version = "4.5", features = ["derive", "env", "color"] }

# libp2p for multiaddr validation
libp2p = { version = "0.56", features = ["macros"] }

# Async runtime for signal handling
tokio = { version = "1.0", features = ["signal", "macros", "rt"] }

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# File system operations
fs_extra = "1.3"
